
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

var _id = "mmir-plugin-tts-speakjs";
var _paths = {
  "mmir-plugin-tts-speakjs/speakGenerator": "www/speakGenerator.js",
  "mmir-plugin-tts-speakjs/speakGenerator.min": "www/speakGenerator.min.js",
  "mmir-plugin-tts-speakjs/ttsSpeakjs": "www/ttsSpeakjs.js",
  "mmir-plugin-tts-speakjs/ttsSpeakjsCompat": "www/alt/ttsSpeakjsCompat.js",
  "mmir-plugin-tts-speakjs/workers/speakWorkerExt": "www/webworker/speakWorkerExt.js",
  "mmir-plugin-tts-speakjs": "www/ttsSpeakjs.js"
};
var _workers = [
  "mmir-plugin-tts-speakjs/workers/speakWorkerExt"
];
var _exportedModules = [
  "mmir-plugin-tts-speakjs"
];
var _dependencies = [];
function _join(source, target, dict){
  source.forEach(function(item){
    if(!dict[item]){
      dict[item] = true;
      target.push(item);
    }
  });
};
function _getAll(type, isResolve){

  var data = this[type];
  var isArray = Array.isArray(data);
  var result = isArray? [] : Object.assign({}, data);
  var dupl = result;
  if(isArray){
    dupl = {};
    _join(data, result, dupl);
  } else if(isResolve){
    var root = __dirname;
    Object.keys(result).forEach(function(field){
      result[field] = root + '/' + result[field];
    });
  }
  this.dependencies.forEach(function(dep){
    var depExports = require(dep + '/module-ids.gen.js');
    var depData = depExports.getAll(type, isResolve);
    if(isArray){
      _join(depData, result, dupl);
    } else {
      Object.assign(result, depData)
    }
  });

  return result;
};
module.exports = {id: _id, paths: _paths, workers: _workers, modules: _exportedModules, dependencies: _dependencies, getAll: _getAll};
