
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *        Do not modify: ANY CHANGES WILL GET DISCARDED              *
 *********************************************************************/

module.exports = {
  pluginName: "ttsSpeakjs",
  config: [
    /** OPTIONAL
     * [custom option]
     * NUMBER Additional gap between words in 10 ms units, i.e. `1` corresponds to a 10 ms duration
     * @default 0
     */
    "wordgap",
    /** OPTIONAL
     * [custom option]
     * The speed at which to talk (words per minute)
     * @default 175
     */
    "speed",
    /** OPTIONAL
     * [custom option]
     * The voice pitch
     * @default 50
     */
    "pitch",
    /** OPTIONAL
     * [custom option]
     * How loud the voice will be
     * @default 100
     */
    "amplitude",
    /**
     * the plugin type
     * @default "tts"
     */
    "type",
    /** the plugin/module which which will load/use this specific TTS implementation
     * @default mmir-plugin-tts-core-xhr.js
     */
    "mod"
  ],
  defaultValues: {
    wordgap: 0,
    speed: 175,
    pitch: 50,
    amplitude: 100,
    type: "tts",
    mod: "mmir-plugin-tts-core-xhr.js"
  },
  speechConfig: [
    /** OPTIONAL
     * NOTE there is only one voice per language, so voice and language are synonymous
     * @see #language */
    "voice",
    /** OPTIONAL
     * @see #voice */
    "language"
  ]
};
